### ISSUE TITLE
Should a product belong to 1 category or more

### ISSUE THREAD

**Issue by MelvinVermeer** [soulve-innovations/hospital-product-catalog-MelvinVermeer#1]
@jboliveira Do you think a product should belong to more than 1 category?

> For products, we need to store their code(unique), description, list of
barcodes(unique), quantity, unit of measurement(for example, pack, box
and unit), expire date, and their respective categories.

My assumption for a real world scenario would be that it is only 1. If it were multiple I'd recommend a name like `Labels` or `Tags`.

However, for the purpose of this assignment you might want to see it differently (n-n relationschip).
So i'm just checking.

**Comment by MelvinVermeer** [comment]
Since there is no answer yet I am going to make the assumption that a product can be in only 1 category. Just as a proof of knowledge I'm sharing what I would do if it needed multiple categories per product:

Many-many relationships without an entity class to represent the join table are not yet supported in Entity Framework. So I would include an entity class for the link table and mapping two separate one-to-many relationships.

In `OnModelCreating()` :

```C#
modelBuilder.Entity<ProductCategory>().HasKey(link => new { link.ProductCode, link.CategoryCode });
modelBuilder.Entity<ProductCategory>()
    .HasOne(link => link.Product)
    .WithMany(product => product.ProductCategories)
    .HasForeignKey(link => link.ProductCode);
modelBuilder.Entity<ProductCategory>()
    .HasOne(link => link.Category)
    .WithMany(product => product.ProductCategories)
    .HasForeignKey(link => link.CategoryCode);
```

The link entity 

```C#
public class ProductCategory
{
    public int ProductCode { get;set;}
    public Product Product { get; set; }
    public int CategoryCode { get;set;}
    public Category Category { get; set; }
}
```

When exposing the Product object to the outside world I would hide the link object, for example with automapper it would look like this:

```C#
CreateMap<Product, Data.DTO.Product>()
    .ForMember(dest => dest.Categories, opt => opt.MapFrom(src => src.ProductCategories.Select(link => link.Category)));
```

**Comment by jboliveira** [comment]
Sorry for the delayed response and your assumption is correct, a product have only 1 category. I will review the assignment and make it clear.

Also, your approach for Many-to-Many is correct. It isn't required for this assignment, but really important to know that you have the knowledge for it.

Thank you Melvin
